vanvalenlab/deepcell-label

- desktop/caliban.py
This change only alters how the labels are displayed without altering the values of the masks.
> Color range of annotated labels can now be adjusted via scrolling

- README.md
- desktop/caliban.py
- desktop/mode.py
Feature adds the ability to delete a cell mask by selecting a cell and pressing the 'X' key. Delete feature only removes mask from the current frame. If the current frame is the only frame that the selected cell appears in, the rest of its lineage data is deleted.
> Cell deletion feature

- desktop/caliban.py
- desktop/mode.py
Fixes some of the formatting issues with the UI prompts. For example, previously when confirming the watershed command the UI did not display "(SPACE=YES / ESC=NO)" as with all the other commands.
> Fixed text formatting in UI prompts

- browser/application.py
- browser/caliban.py
- browser/static/css/main.css
- browser/static/js/main_track.js
- browser/static/js/main_zstack.js
- browser/templates/index_track.html
- browser/templates/index_zstack.html
Fixes trk bugs analogous to npz bugs that were fixed in #63. Cleans up some html/css for both trk and npz files and reduces payload that application.py sends by removing edit_image, since trk mode no longer needs this.
> Update browser trk mode

- desktop/caliban.py
> 95th percentile scaling

- browser/static/js/main_zstack.js
- browser/templates/index_zstack.html
- browser/templates/infopane_abridged.html
Closes #133, #134, #135, #137.
> Misc small changes to rgb

- README.md
Addresses part of #47. Minimizes risk of being in incorrect working directory when running new docker image.
> Update readme with correct path for mounting docker container

- browser/static/js/adjust.js
Reading through I noticed a few minor code cleanup changes to make, and used a local ESLinter to clean up everything I could. No functionality was changed, but below is a summary of edits.
- snake_case variables were transformed to camelCase
- fixed any whitespace issues (with `=` operators and added space between `function {`.
- changed any once-assigned variables to `const`.
- Use single quotes `'` instead of double quotes `"`.
- Added a couple more TODOs, mostly about assumptions of existing variables.
> Cleaned up the JS a bit using ESLint

- .github/workflows/browser-tests.yaml
* Update the cached requirements file to `browser/requirements.txt`.
* Caching the proper file for the browser tests speeds up the builds.
> GitHub actions

- deepcell_label/url_loaders.py
- visualizer/src/FileUpload.js
- visualizer/src/Load.js
* Added `ImageAxesDropDown`, a new subcomponent that sets the `imageAxes` state of the `FileUpload` component.
* This allows the user to upload images of various dimension ordering.
---
Note: Because the page redirects once the file is uploaded, users must select the dimension ordering BEFORE they upload the file. If we want to do otherwise, we will need to change the `FileUpload` component to require a submit button.
Note 2: there is currently little validation done on the backend, so if the user submits the wrong dimension ordering, it can lead to quite a few backend requests.
> Add a form to the `Load` page to capture the image's dimension ordering.

- backend/deepcell_label/loaders.py
- frontend/src/Project/service/idbWebWorker.js
- frontend/src/Project/service/labels/arraysMachine.js
- frontend/src/Project/service/labels/cellsMachine.js
- frontend/src/Project/service/labels/segmentApiMachine.js
This fixes undo after editing the segmentation. It also catches a bug with the cells not persisting on reload immediately after editing the segmentation and adds TODO comments for #347.
> Fix undoing edits to the segmentation

- backend/deepcell_label/export.py
- backend/deepcell_label/export_test.py
- backend/deepcell_label/loaders.py
- documentation/FIRST_TIME_SETUP.md
- documentation/LABEL_FILE_FORMAT.md
- frontend/src/Load/ExampleFileSelect.js
- frontend/src/Project/ProjectContext.js
- frontend/src/Project/cells.test.ts
- frontend/src/Project/cells.ts
- frontend/src/Project/service/hoveringMachine.js
- frontend/src/Project/service/idbWebWorker.js
- frontend/src/Project/service/labels/arraysMachine.js
- frontend/src/Project/service/labels/cellsMachine.js
- frontend/src/Project/service/labels/segmentApiMachine.js
Addresses #347. I decided this was a more critical issue as loading and editing any mesmer results exposes the issue. I did not add "channel mode" editing controls to edit cells across multiple segmentation channels because mesmer does not have consistent cells between channels anyways.
Please user test this (do a handful of actions, undo them, redo them, reload them, combinations of these) on label-dev.deepcell.org!
> Add c to cells

- .github/workflows/precommithooks.yaml
- .pre-commit-config.yaml
- frontend/yarn.lock
* Dependabot updates
* flake8 precommit fix
> Dependency updates

- backend/deepcell_label/export.py
* Fixes a bug where an error is thrown when trying to load in an image/frame with 0 cells, as a relevant function assumed a non-empty list of cells.
> BUG: fix bug when no cells on canvas.

- frontend/cypress/e2e/label.cy.js
* Make e2e test creation from file conditional on AWS keys
* Allow the CI to pass when PRs originate from forks
> CI: Try minimal e2e condition.

- .github/workflows/precommithooks.yaml
- .github/workflows/tests.yaml
Bump action versions to keep CI current, c.f. https://github.com/vanvalenlab/deepcell-tf/pull/653
> Bump default actions to latest version.

- .github/workflows/auto-deploy.yaml
* Describe high-level what changed.
* Provide the justifications for the changes.
> Setup auto deploy actions

- .github/workflows/auto-deploy.yaml
* Describe high-level what changed.
* Provide the justifications for the changes.
> Auto deploy

- backend/deepcell_label/export.py
- frontend/src/Project/Canvas/ToolCanvas/AddCellTypeCanvas.js
- frontend/src/Project/Canvas/ToolCanvas/AddDaughterCanvas.js
- frontend/src/Project/Canvas/ToolCanvas/OutlineCellCanvas.js
- frontend/src/Project/service/exportMachine.js
- frontend/src/Project/service/loadMachine.typegen.ts
- frontend/src/Project/service/raw/rawMachine.js
* Channel names were not exported when a project is exported, meaning that most importantly submitting a project makes the channel names disappear upon loading from the output bucket
* This is now implemented
> Export channels on submit/download

- frontend/cypress/e2e/label.cy.js
- frontend/src/Project/DisplayControls/RawControls/RGBControls.js
- frontend/src/Project/Instructions/CellTypeInstructions.js
- frontend/src/Project/Instructions/DisplayInstructions.js
- frontend/src/Project/Instructions/InstructionsModal.js
- frontend/src/Project/Instructions/PlottingTrainingInstructions.js
* Fixes and revamps the layout display section of the instructions, addressing #447 
* Updates the cell types relevant sections of the instructions with the new buttons and features (cell info, new tool bar and modes, etc.)
> Update instructions panel with bug fix and new cell type features

- backend/deepcell_label/label.py
> MAINT: Followup to matplotlib removal.

- documentation/FIRST_TIME_SETUP.md
- documentation/LOCAL_USE.md
Updates the documentation with more detail and troubleshooting tips for first time set up, local use, and local testing.
> Update documentation for set up and testing
