desktop/caliban.py

Fixes bug where tracks created with watershed have the same ID as a track produced using the create track command when the create track command is used after watershed.
The action_new_track function, which is called when creating a new track, incremented the self.num_tracks  variable, while the action_watershed function did not. By having the action_watershed function increment self.num_tracks, the issue is resolved.

Fixed watershed track creation

---

desktop/caliban.py

Previously, attempting to open track files with large or abnormal dimensions would cause an error with the screen scaling by setting the scale factor to zero. This prevents the scale factor from being set to zero.

Fixed bug with screen scaling with large files

---

desktop/caliban.py

Cells can now be highlighted bright red. Highlighting mode is toggled by pressing H. When highlighting mode is activated, the currently selected cell(s) are highlighted. If a single cell is highlighted, the currently highlighted cell can be selected with the + and - buttons, which cycles which cell ID is currently being highlighted. The highlighted cell(s) along with whether highlighting is enabled is displayed in text labels at the top right of the screen, underneath the frame label. Up to two cells can be selected at a time. Also, clicking an empty region of the frame now has the equivalent effect as pressing escape and deselects any selected cells and resets which cells are being highlighted.

Cell highlighting feature

---

desktop/caliban.py
desktop/mode.py

User can now use the swap feature to swap cells on only current frame instead of all frames. When S is pressed to call the swap feature, the prompt will ask the user to either press S again to swap for a single frame, Space to swap in all frames, or Escape to cancel.

Single Frame Swap Feature

---

desktop/caliban.py

When saving, checks if there are any tracks that do not contain any frames and deletes them. Credit to Geneva for (most) of the code :)

Fixes bug with empty tracks persisting in trk file

---

browser/requirements.txt

Caliban (Browser) requirements pinned an old Pillow version with a vulnerability. Amended to requirements.txt to keep up to date.

Upgrade Pillow version

---

browser/application.py
browser/caliban.py
browser/static/js/main_track.js
browser/static/js/main_zstack.js

browser/caliban.py keeps track of whether actions change the annotations or info, which application.py uses to send the appropriate payload (if frames change, send the updated frame, if info changes, send the updated info) in response to the action.
Also cleans up related code (removes unnecessary ajax/flask functions, cleans up TrackReview and ZStackReview attributes, use np.where for all pixel-editing actions).

Consolidate browser actions to use just one POST request

---

browser/caliban.py
browser/static/js/main_track.js
browser/static/js/main_zstack.js
browser/templates/index_track.html
browser/templates/infopane.html

Splits big, unwieldy functions like prepare_canvas into helper functions. Largely does not change functionality except for a few small improvements, which include:
- redundancy in some functions removed (eg, prepare_canvas had two separate bindings for mouse movement)
- logic before sending some actions reduces unnecessary server calls and chances of buggy behavior (eg, don't send an action to replace a label with itself)
- assigning the same daughter to a parent more than once no longer produces duplicate daughter entries
- limiting how much users can manually increment edit_value of brush may reduce skipped labels
- label_under_mouse would sometimes log errors to the console when mouse moved over edges of canvas, when reported location was out of bounds of seg_array (not noticeable …

Refactor (browser)

---

desktop/caliban.py
desktop/mode.py

Moderate refactor of desktop npz class (ZStackReview) to split functions into smaller pieces. 
Adds documentation (docstrings and comments) throughout class. Updates some minor behaviors (draw_line makes box around image, actions use the frame where they were activated instead of current_frame, add_cell and del_cell helpers added to some actions just in case, add ability to open files that don't contain annotations). Changes how some pieces are put together without changing behavior (screen_scale moved to on_resize, update "slices" info when modifying cell_info instead of on_draw). Removes active contour prediction because it was not very useful (and to free up a keybind).

Refactor, document desktop npz class

---

desktop/caliban.py

Initial refactoring into classes to make Caliban more modular. CalibanWindow class handles window size, binds window events, generates and draws text and images, and does some mouse event handling. CalibanWindow is now the parent class of TrackReview and ZStackReview. CalibanBrush stores brush attributes (different editing values, state of brush tool) and contains methods for updating its attributes and drawing. TrackReview and ZStackReview each create a CalibanBrush object upon initialization.
Minor visual improvements added: add a small blank border around each side of displayed image, display more information to sidebar about displayed image, view applied image adjustments while looking at raw image (in label-editing mode).
Minor changes to TrackReview: working with trk files is now …

Desktop/CalibanWindow, CalibanBrush classes

---

browser/caliban.py
browser/static/js/main_track.js
browser/static/js/main_zstack.js

Outline information about labels is sent by flipping the sign of labels in the array that gets sent to the frontend. Does not change how highlighting currently works in trk or npz files, but is a precursor to updating highlighting in those files + being able to show appropriate label overlays in RGB mode.

Add outline capability to browser

---

browser/eb_application.py

Adds some tracking metrics, including timestamps, to SQL database used with browser caliban. Instead of deleting row from database when file is finished, replaces long data blob with null to clear space. Keeps track of timestamps such as when file is opened and submitted. Keeps track of number of updates submitted to file. Helpful for determining how long files take to annotate, and how that time breaks down. Should also help database maintenance by making it easier to drop stale rows.
I think this is a solid start re: #109. I would be satisfied with closing that issue and opening a separate issue later if we need more advanced metrics or other changes to the SQL code.

Initial timestamp tracking

---

browser/caliban.py
desktop/caliban.py

Addresses #94 across all modes (browser, desktop, trk, npz). If watershed algorithm produces only a few pixels (of either new label or old label), use dilation to expand the label to make it slightly easier to see/select. Small bugfix for desktop trk watershed included (bugfix is already incorporated into other modes but missed desktop trk class).

Watershed failsafe (label dilation)

---

browser/application.py
browser/caliban.py
browser/eb_application.py
browser/static/js/main_zstack.js
browser/templates/index_zstack.html

Add ability to parse optional url args (pixel_only, label_only, rgb). pixel_only and label_only disable certain keybinds to restrict range of functionality available to annotators. rgb toggles change in how images are displayed (how image is generated by server, how labels and overlay are displayed in frontend), and disables certain keybinds that are not relevant to multichannel images.
Addresses #92 (may want to expand on this before closing issue), closes #108.

Initial url options, RGB mode

---

browser/static/js/brush.js

Increase brush size to 5 and opacity from 0.2 to 0.3. Size increase helps to see brush initially, opacity increase helps with translucent trace. Closes #128; does not change label outlines until drawing is applied by server, but helps make path of brush easier to see.

Update initial brush params

---

browser/.ebextensions/healthcheckurl.config
browser/caliban.py
browser/eb_application.py

Create health-check route and configure elastic beanstalk to use it, closes #86 (prevents file uploads from getting lost).
Upload npz and trk files to s3 from file objects, not files saved to disk, closes #106.

Fix npz upload issues

---

browser/README.md
browser/blueprints.py
browser/caliban.py
browser/static/css/main.css
browser/static/js/adjust.js
browser/static/js/brush.js
browser/static/js/main_zstack.js
browser/templates/form.html
browser/templates/index_zstack.html
browser/templates/infopane.html
browser/templates/infopane_abridged.html

- change how images are stored and displayed
- image loading triggers a cascade of image modification and storage to Image objects
- changes to certain variables (eg, image contrast) trigger appropriate parts of the image modification cascade
- image cascade prevents image flickering (new images are not rendered until all images in cascade are loaded and ready to display), allows for scaling, panning, and zooming, and improves image processing (images are processed once, instead of continually while being displayed; original size images are processed and scaled during display, instead of processing scaled images)
- addresses #140 
- displayed canvas size scales appropriately to match available space in window
- images that are too large for space are scaled to be smaller while maintaining …

Update npz canvas (expansion, better scaling, pan+zoom)

---

browser/application.py
browser/blueprints.py
browser/templates/index.html

Add a logger statement and a timer to help identify the longest-taking functions.
Also:
- Minor updates to docstrings.
- Removed redundant `str()` call when creating the template name.
- Updated description of NPZ files on landing page.

Add logger statements to most routes.

---

desktop/caliban.py

Modified rescaling function to pass over channels that are completely empty to avoid 0 indexing errors. 
We previously padded empty channels with mostly blank images, I switched fully blank images so that in the future we can have logic that treats fully empty channels differently.

skip rescaling for empty channels

---

browser/blueprints.py

[distutils.util.strtobool](https://docs.python.org/3/distutils/apiref.html#distutils.util.strtobool) is a standard library tool that maps strings to `0` and `1`.
> True values are `y`, `yes`, `t`, `true`, `on` and `1`; false values are `n`, `no`, `f`, `false`, `off` and `0`. Raises `ValueError` if _val_ is anything else.
Fixes #161

Use distutils.util.strtobool to cast boolean request args to bools.

---

browser/imgutils.py
browser/requirements.txt

`PIL` is much faster than `matplotlib`. I could not find a way to replace the `matplotlib` functions while still using a color map, but if no cmap is provided, we can use PIL to speed it up significantly.
Related to #68 and #142

Use PIL to create PNGs if not using a cmap.

---

browser/.gitignore
browser/blueprints.py
browser/caliban.py
browser/static/js/main_track.js
browser/static/js/main_zstack.js

This PR prevents the API from returning raw data on every action request, when actions only manipulate the annotations.  I've adapted the JS so that if the action _does_ include raw in the payload it will overwrite it currently, otherwise it just sets `rawLoaded = true`.
Are there any actions that will require an update to the raw image data?
Related to #68 and #142

Don't need to return raw data on action requests.

---

browser/caliban.py

Close #160. For historical reasons we may have npzs still floating around saved with variable names `raw` and `annotated` instead of `X` and `y`, so these npzs should still be loaded by caliban, but we have no particular reason not to save them as `X` and `y` going forward.

Save npzs with X and y

---

browser/static/js/adjust.js
browser/static/js/main_zstack.js

Adds option, in non-rgb pixel-only mode, to hide labels with "L" key, as users can't leave pixel-editing mode to view the raw-only image. Doesn't change existing rgb "L" functionality. Adds intermediate step to image processing cascade so that the adjusted, un-composited raw image can be easily displayed when "L" is toggled. Closes #173
Also addresses small bugs encountered while making instructions for HeLa movies:
- thresholding failed if no labels existed, due to edge case behavior when determining the maximum label value. Didn't seem to affect anything other than thresholding. Fixed by specifically accounting for that edge case
- setting the conversion brush with clicking would register the click locations as part of the `mouse_trace` and send those click coordinates next time the …

Hide labels, bugfixes

---

browser/static/js/brush.js

Clean up some minor ESLint issues in `brush.js`.
- Fix whitespace
- Use `const` instead of `let` where possible (variable is only assigned once).
- Use `document.getElementById` instead of `$('#')` to remove jquery dependency.

ESLint brush.js

---

browser/requirements.txt

Several CVEs were found for Pillow < 7.1.0:
- CVE-2020-11538
- CVE-2020-10379
- CVE-2020-10994
- CVE-2020-10177

Update Pillow>=7.1.0 to resolve several moderate CVEs

---

desktop/caliban.py

Closes #177 by adding try/except statements to file saving functions.

Prevent desktop caliban crash if file can't be saved

---

README.md
desktop/caliban.py

Closes #185. Option to toggle visibility used to be more useful when pixel-editing mode was in development. We no longer need the option, so removing it will free up a keybind and make desktop caliban slightly less complex.
- remove keybind from ZStackReview, TrackReview
- remove mention of keybind from readme

Remove cursor visibility toggle from desktop version

---

browser/static/js/main_zstack.js

Should not have been removed in earlier changes. When the mouse moves, the underlying image may not change but the specific info displayed often does.

bugfix (update displayed info when mouse moves)

---

browser/static/js/adjust.js
browser/static/js/main_zstack.js

Add a white outline to highlighted label in non-rgb pixel-editing mode to help distinguish labels from each other. Highlighting already recolored current label to red, but the semi-translucency of the label could still make it a little difficult to see exactly where the boundaries were. This change makes the highlighting behavior more similar to desktop version (label is outlined but not changed to red) and to how the conversion brush labels are shown in non-rgb pixel-editing mode.
Example:

add a white outline to highlighted pixel-editing label

---

.gitignore
README.md
browser/README.md
setup.py

Change Caliban to DeepCell Label in main README and browser README. Did not change caliban.py
Name change before Janelia workshop

Change Caliban to DeepCell Label in READMEs

---

browser/blueprints.py
browser/blueprints_test.py
browser/caliban.py
browser/config.py
browser/conftest.py
browser/models.py
browser/models_test.py
browser/static/js/main_track.js
browser/static/js/main_zstack.js
browser/templates/tool.html

This PR adds the schema changes needed by the file-loader PR #214  to the master branch without functionality of #214. The schema changes all affect the Projects table and include:
- using only a `path` column instead of both a `filename` and a `path` column
- remove the `output_bucket` column
- add a `token` column that gives Projects a unique 12 character base64 identifier
- add a `source` column that records where a project was loaded from (currently always `s3`)
In line with these schema changes, we also change:
- the internal `load` and `upload_file` routes now include a `bucket` component like `/load/<bucket>/<projectID>`
- the `create` function and Project constructor now only have two arguments, `path` and `bucket`, instead of `filename`, `path`, `input_bucket`, and …

File loader schema bridge

---

browser/static/js/history.js

This is a quick bug fix that affects reloading the action history when revisiting a project URL. The constructor for a ChangeFrame action changed between #212 and #214, but did not change in initializeActionHistory, causing the frames to not change while undoing past actions after reloading the page.
One issue highlighted by this fix is that initializeActionHistory does not switch between features when past actions occurred on different features. I made an issue #220 to document this.
When actions occur on different frames, we should switch to the frame where the action occurs before undoing it so that the changes are visible.

Fix action history initialization to change frames correctly

---

README.md
deepcell_label/src/controller.js
deepcell_label/src/statechart.js
deepcell_label/templates/partials/infopane.html

Fixes some typos & adds some excerpts from previous workshop material to the dropdown documentation.
Two functional changes:
- prevent default behavior for Ctrl+B (which is a bookmark shortcut in Firefox)
- rerender the canvas on state transitions so the brush appears immediately when switching to the brush tool
Trying to get in some last-minute polish before the Label workshop later today.

Bebi 205 documentation

---

deepcell_label/blueprints.py
deepcell_label/templates/tool.html

These are hotfixes for submitting jobs from Anolytics to call the correct route and avoid finishing projects so that project URLs remaining usable for QC.

Upload fix

---

.editorconfig

* Add an `.editorconfig` file with standards set for JS and Python.
* Standardize some editor configuration settings, namely indent-spacing.

Add an .editorconfig file to standardize file types.

---

deepcell_label/label.py
deepcell_label/label_test.py
visualizer/src/service/tools/toolMachine.js
visualizer/src/service/tools/trackMachine.js

* Change the named arguments for `replace_with_parent` from the old `label_1`/`label_2` to just `daughter`.
* The backend was hitting 500 errors due to named argument errors.

Update named parameters for `replace_with_parent`.

---

visualizer/src/Controls/Segment/ActionButtons/ReplaceButton.js
visualizer/src/Controls/Segment/ActionButtons/SwapButton.js

Swap and replace can cause drastic changes to the labeling, in particular filling all the unlabeled areas when swapping or replacing the `0` label. Changing the hotkeys from S to Shift + S and R to Shift + R makes these actions harder to accidentally do.

Update swap and replace hotkeys

---

visualizer/src/service/projectMachine.js
visualizer/src/service/selectMachine.js

I noticed when debugging Anolytic's issue this morning with not being able to make new labels that the selected labels were not changing when undoing and redoing. The segmentMachine used to manage the selected labels, so they were undone and redone through this machine, so it looks like we never added the selectMachine to the undo/redo history.

Track selected labels for undo/redo

---

visualizer/src/Canvas/Tool/BrushCanvas.js
visualizer/src/Canvas/Tool/ThresholdCanvas.js
visualizer/src/Controls/Segment/ActionButtons/AutofitButton.js
visualizer/src/Controls/Segment/ToolButtons/BrushButton.js
visualizer/src/Controls/Segment/ToolButtons/EraserButton.js
visualizer/src/Controls/Segment/ToolButtons/FloodButton.js
visualizer/src/Controls/Segment/ToolButtons/SelectButton.js
visualizer/src/Controls/Segment/ToolButtons/ThresholdButton.js
visualizer/src/Controls/Segment/ToolButtons/TrimButton.js
visualizer/src/Controls/Segment/ToolButtons/WatershedButton.js
visualizer/src/ProjectContext.js
visualizer/src/service/canvasMachine.js
visualizer/src/service/projectMachine.js
visualizer/src/service/selectMachine.js
visualizer/src/service/tools/segment/brushMachine.js
visualizer/src/service/tools/segment/floodMachine.js
visualizer/src/service/tools/segment/selectMachine.js
visualizer/src/service/tools/segment/thresholdMachine.js
visualizer/src/service/tools/segment/toolUtils.js
visualizer/src/service/tools/segment/trimMachine.js
visualizer/src/service/tools/segment/watershedMachine.js
visualizer/src/service/tools/segmentMachine.js

When using tool hotkeys to switch out the brush and threshold currently causes UI crashes as the tool changes before the `BrushCanvas` or `ThresholdCanvas` is removed, causing these canvases to access a brush machine or threshold machine that no longer exists. 
Previously, we spawned one tool machine at a time and deleted the previous tool machine when switch between tools. With this PR, we spawn all of the tools and keep them in the `segmentMachine` and switch between these pre-existing tool. Instead of a `useTool` hook that provides the current tool, we have specific `useBrush` and `useThreshold` hooks that provide the persistent brush or threshold actors so these components don't crash even if the component is out of sync with the current tool.
This PR also includes a couple of fixes …

Fix tool keybinds

---

.github/release-drafter.yml
.github/workflows/release-drafter.yaml

* Add the `release-drafter` GitHub Action workflow and template
* Automatically draft the next release based on the labels of the changes.
* Saves a lot of time in building releases.
* Consistent style for all the DeepCell project releases.

Add new release-drafter GitHub Workflow.

---

requirements-test.txt

* Pin the `coveralls` version to be < 3.3.0.
* `coveralls` released [version 3.3.0](https://pypi.org/project/coveralls/) yesterday which is causing [builds to break](https://github.com/vanvalenlab/deepcell-label/runs/4111480977?check_suite_focus=true). This change prevents the new version from being installed.

Put a version ceiling on coveralls, 3.3.0 has a bug preventing builds.

---

visualizer/package.json
visualizer/src/App.js

React Router released a [new major version 6](https://remix.run/blog/react-router-v6) which has more flexible hooks and is more composable. It replaces the <Switch> component with <Routes> which avoids bugs due to route ordering and lets us place the `/` route before the `/project` route, which @willgraf requested in a recent review.

Upgrade to react-router v6

---

README.md

Issue #284 had issues with setting environment variables. Adding some instructions to the readme on how to use the example `.env.example` will point users to the resources to configure their envvars correctly.

Add instructions on .env to README

---

.github/workflows/tests.yaml
convert.py
deepcell_label/__init__.py
deepcell_label/blueprints_test.py
deepcell_label/exporters_test.py
deepcell_label/imgutils_test.py
deepcell_label/label_test.py
deepcell_label/labelmaker_test.py
deepcell_label/loaders_test.py
pytest.ini
requirements-test.txt

In #287, we drop support for Python 3.6, but did not test for the newer Python releases 3.9 and 3.10. Here we add them to our test matrix to make sure our codebase works for these versions for when we'll need to switch to them down the road.
However, pytest-pep8 is incompatible with Python 3.10. Python 3.10 requires at least pytest 6.2.4 per [this issue](https://github.com/pytest-dev/pytest/issues/8539) and pytest-pep8 is incompatible with pytest 6, as seen in this error message
```
Direct construction of Pep8Item has been deprecated, please use Pep8Item.from_parent.
See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.
```
As [pytest-pep8](https://pypi.org/project/pytest-pep8/) is not an actively mantained project and the …

Add testing for python 3.9 and 3.10

---

visualizer/src/Canvas/ComposeCanvases.js
visualizer/src/Canvas/Labeled/LabeledCanvas.js
visualizer/src/Canvas/Labeled/OutlineCanvas.js
visualizer/src/Canvas/Raw/RGBCanvas.js
visualizer/src/Canvas/Tool/BrushCanvas.js
visualizer/src/Canvas/Tool/ThresholdCanvas.js
visualizer/src/ProjectContext.js

With the most recent pull request #294, I noticed that Firefox and Chrome handled the new canvas as expected, but Safari was not behaving correctly. It seems that that Safari only received WebGL2 support in Safari 15 released a few months ago with macOS 15: [https://caniuse.com/webgl2](https://caniuse.com/webgl2).
I fixed the initialization of the GPU-accelerated contexts to check which context is available in the browser and set one or the other up as needed. I also had issues with the WebGL canvases clearing their data after being drawn, causing it to appear once and then to appear blank in later renders. To fix this, I drew the WebGL kernel output onto a separate canvas as soon as it is created, and this other canvas with a standard 2d context does not get cleared when drawn. This …

Fix GPU.js handling of WebGL

---

visualizer/src/Controls/FrameSlider.js
visualizer/src/Controls/ImageControls/ImageControls.js
visualizer/src/Controls/Segment/SelectedPalette.js
visualizer/src/Controls/SegmentControls.js
visualizer/src/Controls/Tracking/Division.js
visualizer/src/Controls/Tracking/LabelTimeline.js
visualizer/src/Controls/Tracking/Timeline.js
visualizer/src/Controls/TrackingControls.js
visualizer/src/Label.js
visualizer/src/Load/FileUpload.js
visualizer/src/ProjectContext.js
visualizer/src/index.tsx

This adds in a couple of fixes, mostly for tracking jobs, including
- enabling uploading .trk from the homepage
- removing an extra FrameSlider above the image controls
- hiding the Frame label when FrameSlider is hidden
- fixing the colors provided to the Division components to be provided in hex format instead of a list of [r, g, b]

Fixes for tracking before release

---

visualizer/src/Canvas/Labeled/LabeledCanvas.js
visualizer/src/Canvas/Labeled/OutlineCanvas.js
visualizer/src/Canvas/Raw/ChannelCanvas.js
visualizer/src/Canvas/Raw/GrayscaleCanvas.js
visualizer/src/Canvas/Tool/ThresholdCanvas.js

Our minified production code replaces expression like `if (x) { y }` to `x && y`, breaking how GPU.js compiled functions into a kernel. By wrapping the functions in ticks, they won't be minified and all the syntax is preserved for GPU.js when it compiles the function at runtime.
These issues on the GPU.js repo detail this: 
[https://github.com/gpujs/gpu.js/issues/152 ](https://github.com/gpujs/gpu.js/issues/152) 
[https://github.com/gpujs/gpu.js/issues/584](https://github.com/gpujs/gpu.js/issues/584)

Wrap GPU.js kernel functions in templates

---

.github/workflows/tests.yaml

Our frontend testing suite has started failing on the yarn install step because Node 12 has reached its end of life. This PR drops node 12 from the testing matrix.

Remove node 12 from testing matrix

---

.ebextensions/files.config
.platform/nginx/conf.d/proxy.conf

As reported in #305, drag and drop is not working on the label.deepcell.org homepage due to the 413 errors reporting that attached files are too large.
I believe with our update to Amazon Linux 2 for the backend in #287, the behavior for nginx changed. With this new platform, the configuration looks a bit different/ With the previous platform, we would [set up this file with a `.config` file ](https://stackoverflow.com/questions/18908426/increasing-client-max-body-size-in-nginx-conf-on-aws-elastic-beanstalk) but with Amazon Linux 2, [this approach no longer works ](https://stackoverflow.com/a/70959127/14458070) and instead we put the conf file in the `.platform` folder.

Set file upload size limit to 50 megabytes

---

.github/workflows/tests.yaml
.pre-commit-config.yaml
requirements.txt

I have been seeing this error come up in the backend logs when users try to load tiffs from the Label homepage.
```
ValueError: <COMPRESSION.LZW: 5> requires the 'imagecodecs' package
```
This adds imagecodecs to the requirements for the backend. It also drops Python 3.7 from our testing matrix as the latest release of imagecodecs is for Python 3.8+ per this NEP (like PEP for numpy) https://numpy.org/neps/nep-0029-deprecation_policy.html. We now use Python 3.8 for hosting on Elastic Beanstalk, so this matches our use.

Add imagecodecs to requirements

---

.github/workflows/tests.yaml
Dockerfile
deepcell_label/export.py
deepcell_label/loaders.py
deepcell_label/loaders_test.py
documentation/FIRST_TIME_SETUP.md

This addresses some quick fixes for loading from deepcell.org/predict (now online!). 
The first issue was from an incorrect test case that caused loading zips of tiffs with batches to drop the X dimension.
The second issue was assuming the smallest dimension is the channels when axes are not provided, causing tracking timelapses to use their time axis as channels instead.

Fix loading from deepcell.org/predict

---

backend/requirements.txt
documentation/FIRST_TIME_SETUP.md

When setting up the deepcell label repository with Kevin Yu this week, our incoming schmidt software engineer, there was an issue with using python-magic on windows. Installing python-magic-bin as a python dependency solved the issue.

Add python-magic-bin

---

.github/workflows/tests.yaml

When merging into main for the 0.4 release, the tests didn't run. This gets the tests GitHub Action to run when pushing to main. Coverage for coveralls is based on tests on main, so this will keep the coverage badge up to date.

Run tests when pushing to main

---

.gitignore
backend/deepcell_label/blueprints.py
backend/deepcell_label/config.py
backend/deepcell_label/conftest.py
backend/deepcell_label/label.py
backend/deepcell_label/label_test.py
backend/deepcell_label/loaders_test.py

Addressed the bug from Issue #365, in which after deleting a cell, one cannot write over the deleted cell's area when using exclusion mode. 
Additionally, added some snippets of code required for the tests and source code to run on Windows.
The bug arose because the deleted cell was only removed from the cells matrix but its label persisted in the labels matrix. Added a new function to the Edit class called clean_labels() which deletes any labels that do not correspond to existing cells that is called every time an action is performed that adds masks (eg. brush, flood, etc.). Additionally, a more esoteric bug was found involving overlapped cells reappearing after deletion, which should be addressed by this change as well.
Users can now properly edit areas previously occupied by deleted …

Fix bugs related to cells not properly deleting

---

.gitignore
backend/deepcell_label/blueprints.py
backend/deepcell_label/config.py
backend/deepcell_label/conftest.py
backend/deepcell_label/label.py
backend/deepcell_label/label_test.py
backend/deepcell_label/loaders_test.py
frontend/src/Project/service/idbWebWorker.js

My guess is that after Tom fixed the bug related to adding c to cells, the "feature" field was renamed to "c", so the idbWebWorker was unable to find what segmentation feature was being edited, and segmentations were thus not being tracked.
Users can now reload without losing their segmentation changes (eg. brush adds/removes).

Fix bug causing segmentations to be lost upon reload

---

backend/deepcell_label/blueprints.py
backend/deepcell_label/config.py
backend/deepcell_label/label.py
backend/deepcell_label/loaders_test.py
frontend/src/Project/Canvas/LabeledCanvas.js
frontend/src/Project/Canvas/OutlineCanvas.js
frontend/src/Project/service/idbWebWorker.js

Fixes canvas rendering bugs, namely #366 and #367, which were both caused by issues in the gpu rendering kernel. Specifically, a check is now called to ensure that a value is contained within the bounds of expected values before trying to render the label associated with that value (out of bounds indexing was resulting not in errors but the cells reappearing upon deletion). Additionally, the max number of cells displayed has been increased to 5000.
These changes were tested by Changhua and me and appear to be working properly.
Users can now render up to 5000 cells at once on a canvas and will not experience bugs when deleting the highest valued cells in a given frame.

Fix canvas rendering bugs caused by issues with gpu rendering kernel

---

backend/deepcell_label/export.py
frontend/src/Project/Canvas/ToolCanvas/OuterOutlineCanvas.js
frontend/src/Project/Canvas/ToolCanvas/OutlineCellCanvas.js
frontend/src/Project/EditControls/SegmentControls/ActionButtons/AutofitButton.js
frontend/src/Project/EditControls/SegmentControls/ToolButtons/ThresholdButton.js
frontend/src/Project/service/edit/segment/editSegmentMachine.js
frontend/src/Project/service/loadMachine.ts

* Fixed GPU rendering bugs for the COMBINE and FLOOD tools (#380).
* These tools also rendered outlines when used and ran into the same issues as those fixed in #376, so similar fixes were applied.
* Fixed bugs related to "Cell 0" edits (#382).
* If no cell was selected, it was possible to create cells with label 0 on the canvas. Possible from:
1. Hitting `esc` while using the BRUSH tool. Fixed by switching to SELECT when `esc` is hit.
2. Hitting `esc` to select nothing and then switching to the THRESHOLD tool. Fixed by selecting a new cell when hitting the THRESHOLD tool if current cell is 0.
3. Hitting `esc` to select nothing and then pressing the autofit tool. Fixed by not using the autofit tool if current cell is 0.
* Fixed bug in how raw array was saved in the reshaping.
* Threshold …

Fix GPU rendering bugs, cell 0 bugs, and bug in saving raw array

---

.github/workflows/precommithooks.yaml
.pre-commit-config.yaml

In principle this could use a bigger makeover; specifically reviewing the versions of all the hooks. In practice most of them should be replaced with ruff.
General maintenance to try to get the CI back into a fully operational state.

Update URL to flake8 to fix precommit job.

---

.github/workflows/tests.yaml

According to the cypress-io action docs, env vars prepended this way are automatically forwarded to the cypress environment.
Follow-up to #406 in response to @ykevu 's observation that the test was not being run on `main` post-merge either.
What we expect:
- Test to be skipped on PR opening/push (i.e. `label.` tests will only have 5 tests)
- Test to run post-merge (i.e. `label.` tests will have 6 tests, all green)

Prepend env vars with CYPRESS_

---

frontend/src/Project/EditControls/CellTypeControls/ChannelExpressionPlot.js
frontend/src/Project/EditControls/CellTypeControls/TrainingUI/LearnTab.js
frontend/src/Project/service/labels/channelExpression.test.ts
frontend/src/Project/service/labels/channelExpressionMachine.js

* Adds ability to calculate centroids of each cell in order to spatially visualize them on the plotly chart and graph them
* Adds unit testing for both the new centroid calculations and for the original mean and total calculations in channelExpressionMachine.js

Implement centroid calculations and channel expression unit testing

---

frontend/cypress/e2e/celltypes.cy.js
frontend/src/Footer/Footer.js
frontend/src/Project/EditControls/CellTypeControls/ChannelExpressionPlot.js
frontend/src/Project/EditControls/CellTypeControls/ChannelExpressionUI/AddRemoveCancel.js
frontend/src/Project/EditControls/CellTypeControls/ChannelExpressionUI/Calculate.js
frontend/src/Project/EditControls/CellTypeControls/ChannelExpressionUI/CalculateWholeToggle.js
frontend/src/Project/EditControls/CellTypeControls/ChannelExpressionUI/ChannelSelect.js
frontend/src/Project/EditControls/CellTypeControls/TrainingUI/Hyperparameters.js
frontend/src/Project/EditControls/CellTypeControls/TrainingUI/LearnTab.js
frontend/src/Project/EditControls/CellTypeControls/TrainingUI/TrainingButtons.js
frontend/src/Project/EditControls/CellTypeControls/TrainingUI/VisualizationModal.js
frontend/src/Project/ProjectContext.js
frontend/src/Project/cells.ts
frontend/src/Project/service/labels/arraysMachine.js
frontend/src/Project/service/labels/channelExpression.test.ts
frontend/src/Project/service/labels/channelExpressionMachine.js
frontend/src/Project/service/labels/trainingMachine.js

Addresses #413
* Implemented functions to calculate and visualize mean/total embeddings across all frames
* Implemented UI controls that allow users to specify whether they want to calculate/visualize/train/predict on the current frame or across all frames
* Added documentation to trainingMachine functions since those functions are a bit of a mess
* Added unit tests for new cross-frame calculation functions

Allow calculations and training across all frames

---

.github/workflows/tests.yaml

* Cypress e2e tests have started failing 100% of the time because on Feb 13, 2023, Github began defaulting to Node.js 18. Using the setup-node action to force node version to 16.x should bring us back to where we were before.

Force cypress action to lower version

---

frontend/src/Project/EditControls/CellTypeControls/ChannelExpressionUI/ChannelPlot.js
frontend/src/Project/EditControls/CellTypeControls/ChannelExpressionUI/ChannelSelect.js
frontend/src/Project/EditControls/CellTypeControls/PlotAndLearnTabs.js
frontend/src/Project/service/labels/channelExpressionMachine.js

The UI currently looks pretty ugly and the interfacing between scatter and histogram is still pretty gross (a TODO to potentially also wrap this up in custom plotly buttons could maybe solve this, alternatively hooking into state machine but that might be overkill) but it works. Plotly does indeed have log axes for histograms, I was just looking at the wrong thing.
Also, Plotly related UI stuff is pretty hard to test unfortunately.
Closes #442

Add log y scale button for histogram and save layout changes

---

frontend/src/App.js
frontend/src/Navbar.js
frontend/src/Project/EditControls/CellTypeControls/ChannelExpressionUI/CalculateWholeToggle.js

Adds an icon button to the navbar in the top right to toggle between light and dark mode themes. It turned out that two lines of default dark mode from MUI and adding the cssbaseline component made this essentially good enough out of the box.
Lower priority TODOs:
- The plotly components are still blinding white in dark mode, but they would definitely be a pain to sync up
- Cypress test

Add toggle to NavBar to switch between light and dark mode

---

frontend/src/Project/Canvas/ToolCanvas/AddCellTypeCanvas.js
frontend/src/Project/Canvas/ToolCanvas/AddDaughterCanvas.js
frontend/src/Project/Canvas/ToolCanvas/OutlineCellCanvas.js

In AddCellTypeCanvas.js and AddDaughterCanvas.js, we have:
```python
if (!cell) {
return null;
}
```
I don't have a deep enough understanding of React to know exactly why is the case under the hood, but because of this code, the OutlineCellCanvas component is regenerated without disposing of its memory every time a cell goes from selected to not selected in the context of add mode (which equates to adding a cell to a cell type -> going from returning the component to returning null, alternating). This is especially bad because OutlineCellCanvas calls useCellMatrix(), which is a hook that, if needed, reallocates an approximately N x N matrix where N is the highest ID cell in your current frame. 
Ultimately, this means that for the Keren dataset approximately 120 mb are reallocated …

Fix memory leak caused by continuously returning OutlineCellCanvas

---

frontend/src/Project/EditControls/CellTypeControls/CellTypeControls.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/CellTypeAccordion/CellTypeAccordion.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/CellTypeAccordion/CellTypeCheckbox.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/CellTypeAccordion/EditDeleteMenu.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/CellTypeAccordionList.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/ToggleAll.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/ToolBar.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/ToolBar/AddCellTypeLabel.js
frontend/src/Project/service/labels/cellTypesMachine.js

* The array that controls what cell types are toggled on or off is moved back to the state machine, as it should be--I found that the fix to #470 was because we have to reassign arrays to new arrays for React to tell that a change was made (the Javascript equivalent of having to assign a variable to list.copy() instead of assigning to list)
* I also fixed bugs relating to how the array is initialized and changed when cell types are turned on, turned off, deleted, added, etc. in various combinations
* **TODO**: The array will still bug out if you, say delete a cell type and then undo that deletion (see #427). This can be fixed by making cellTypesMachine register the UI and have the toggle logic (and opacities should fall under this too) tracked with UNDO/REDO; however, this is a bit of a …

Move toggle logic back to state machine, fix various bugs

---

frontend/cypress/e2e/celltypes.cy.js
frontend/src/Project/Canvas/ToolCanvas/CellSelectionCanvas.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeControls.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/ToggleAll.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/ToggleAnimation.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/ToolBar.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/ToolBar/AddCellTypeLabel.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/ToolBar/HighlightMultiLabel.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/ToolBar/HoverToggle.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/ToolBar/ModeToggle.js
frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/ToolBar/OpenMarkerPanel.js
frontend/src/Project/EditControls/EditTabs.js
frontend/src/Project/service/canvasMachine.js

* Addressing #480 and #464 
* We change the multiselect canvas rendering to increase its visibility--the width of the white outlines is increased to 2, and the interior is lit up with white 50% opacity pixels. Additionally, an animation can be enabled that alternates the interior on and off to create a light-up flashing effect (there is a warning on the toggle for people sensitive to flashing lights)
* We leverage this new multiselect to add a button + keybinding to multiselect all cells with multiple labels, for reasoning explained in #464 
* Some additional UI and keybinding tweaks were made for QOL, such as moving tooltip positions and changing keybindings, most notably hover toggle from Shift to X
* Importantly, this canvas can be extended naturally to account for, say, high …

Increase visibility of multiselected cells for general use

---

frontend/src/Project/EditControls/CellTypeControls/CellInfoUI/CellExpressions.js

* Adjusts the height and margin of cell expression plot to account for larger number of channels and variety of channel name lengths as referenced in #484 . This is difficult to test since we don't have a easy way of changing the channel names list so this may have issues again in the future, but the plot looked good for a variety of lists that I looked at (Hickey, Liu, 2d example)

Adjust height and margin of cell expression plot

---

documentation/ARCHITECTURE.md
documentation/LABEL_FILE_FORMAT.md
frontend/src/Footer/Footer.js
frontend/src/Load/Load.js

* Edits the documentation in the file format and the architecture to explain the new state machines and format specifications related to cell types
* Adds a link to the documentation on the landing page to direct users to file format documentation

Update documentation with cellTypes features

---

frontend/src/Project/EditControls/CellTypeControls/CellTypeUI/CellTypeAccordion/EditNameField.js
frontend/src/Project/service/idbMachine.js
frontend/src/Project/service/idbWebWorker.js
frontend/src/Project/service/raw/rawMachine.js

* Fixes a bug where undoing a cell type name change does not update the UI immediately (#448)
* Fixes bug where changing channel names does not update UI immediately (#496) (see description of #473 )
* Channel names are now updated in IDB (aka edited channel names will persist on reload)

Cell type and channel name state management fixes

---

frontend/src/Project/EditControls/CellTypeControls/ChannelExpressionUI/AddRemoveCancel.js

* When there are no cell types the cell type selection component for adding or removing selected cells from a cell type on the right panel throws warnings; by checking if there are cell types, this warning will be suppressed

Remove cell type selection component when no cell types

---

backend/deepcell_label/loaders.py
backend/requirements.txt

* Fix a few instances in the code where `np.stack` was called on non-iterables
* This pattern was deprecated - fixing it allows us to upgrade to latest numpy

MAINT: Fix deprecated code and unpin numpy.

---

backend/deepcell_label/label.py
backend/requirements.txt

Matplotlib was only used in one place for normalization. Replace the usage to reduce dependency footprint.

MAINT: Rm dependency on matplotlib.

---

backend/requirements.txt

Werkzeug v3 removes functionality that flask 2 depends on, but flask 2.0.2 doesn't contain an upper bound pin on the major version of werkzeug, so add it manually here.

MAINT: Pin werkzeug for flask v2 compatibility.
